# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rHESS_SEM
#' @description
#' Run a simple SEM Bayesian sampler
#' @name rHESS_SEM
#' @param inFile path to data file
#' @param outFilePath path to where the output is to be written
#' @param nIter number of iterations
#' @param nChains number of parallel chains to run
#' @param seed pRNG seed
#' @param method $gamma$ sampling method, where 0=$MC^3$ and 1=Thompson -sampling-inspired novel method
#' @examples
#' rHESS_SEM(inFile="Data/sem_data.txt",outFilePath="Data/",nIter=200)
#' 
#' @export
rHESS_SEM <- function(inFile, outFilePath, nIter = 10L, nChains = 1L, seed = 0L, method = 0L) {
    .Call('_rBSEM_rHESS_SEM', PACKAGE = 'rBSEM', inFile, outFilePath, nIter, nChains, seed, method)
}

