# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rHESS_SEM_internal
#' @description
#' Run a simple SEM Bayesian sampler -- internal function
#' @name rHESS_SEM_internal
#' @param inFile path to data file
#' @param outFilePath path to where the output is to be written
#' @param nIter number of iterations
#' @param nChains number of parallel chains to run
#' @param seed pRNG seed
#' @param method \deqn{\gamma}{gamma} sampling method, where 0=\deqn{MC^2}{MC^3} and 1=Thompson -sampling-inspired novel method
NULL

rHESS_SEM_internal <- function(inFile, outFilePath, autoAddIntercept, gammaInit = "S", nIter = 10L, nChains = 1L, seed = 0L, method = 0L) {
    .Call('_rBSEM_rHESS_SEM_internal', PACKAGE = 'rBSEM', inFile, outFilePath, autoAddIntercept, gammaInit, nIter, nChains, seed, method)
}

