// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rHESS_SEM_internal
int rHESS_SEM_internal(std::string inFile, std::string outFilePath, bool autoAddIntercept, std::string gammaInit, unsigned int nIter, unsigned int burnin, unsigned int nChains, unsigned long long seed, int method);
RcppExport SEXP _rBSEM_rHESS_SEM_internal(SEXP inFileSEXP, SEXP outFilePathSEXP, SEXP autoAddInterceptSEXP, SEXP gammaInitSEXP, SEXP nIterSEXP, SEXP burninSEXP, SEXP nChainsSEXP, SEXP seedSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type inFile(inFileSEXP);
    Rcpp::traits::input_parameter< std::string >::type outFilePath(outFilePathSEXP);
    Rcpp::traits::input_parameter< bool >::type autoAddIntercept(autoAddInterceptSEXP);
    Rcpp::traits::input_parameter< std::string >::type gammaInit(gammaInitSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nChains(nChainsSEXP);
    Rcpp::traits::input_parameter< unsigned long long >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(rHESS_SEM_internal(inFile, outFilePath, autoAddIntercept, gammaInit, nIter, burnin, nChains, seed, method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rBSEM_rHESS_SEM_internal", (DL_FUNC) &_rBSEM_rHESS_SEM_internal, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_rBSEM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
